STATUS_PENDING = "PENDING"
STATUS_LEADERSHIP_APPROVED = "LEADERSHIP_APPROVED"
STATUS_DEVOPS_APPROVED = "DEVOPS_APPROVED"
STATUS_REJECTED = "REJECTED"
STATUS_CANCELLED = "CANCELLED"
STATUS_COMPLETED = "COMPLETED"

ACCESS_TYPE_READ = "read"
ACCESS_TYPE_WRITE = "write"

ACCESS_TYPES = {
    ACCESS_TYPE_READ,
    ACCESS_TYPE_WRITE,
}

DECISION_APPROVE = "approve"
DECISION_REJECT = "reject"

LEADERSHIP_DECISIONS = {
    DECISION_APPROVE,
    DECISION_REJECT,
}

ACTION_REQUEST_CREATED = "REQUEST_CREATED"
ACTION_REQUEST_CANCELLED = "REQUEST_CANCELLED"
ACTION_LEADERSHIP_APPROVED = "LEADERSHIP_APPROVED"
ACTION_LEADERSHIP_REJECTED = "LEADERSHIP_REJECTED"

TERMINAL_STATUSES = {
    STATUS_REJECTED,
    STATUS_CANCELLED,
    STATUS_COMPLETED,
}

REQUEST_STATUSES = {
    STATUS_PENDING,
    STATUS_LEADERSHIP_APPROVED,
    STATUS_DEVOPS_APPROVED,
    STATUS_REJECTED,
    STATUS_CANCELLED,
    STATUS_COMPLETED,
}


def normalize_status(status: str) -> str:
    return status.strip().upper()


def can_cancel(status: str) -> bool:
    return status == STATUS_PENDING


def normalize_access_type(access_type: str) -> str:
    return access_type.strip().lower()


def normalize_decision(decision: str) -> str:
    return decision.strip().lower()
